micronaut:
  application:
    name: apiExam
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: jdbc:postgresql://${APIEXAM_DB_HOST:localhost}:${APIEXAM_DB_PORT:54322}/api_exam_db
    driverClassName: org.postgresql.Driver
    username: apiexam
    password: apiexam
    schema-generate: none
    dialect: POSTGRES
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
      default-schema: 'public'
      liquibase-schema: 'public'
endpoints:
  health:
    enabled: true
jackson:
  serialization:
    writeDatesAsTimestamps: false
